services:
  - type: web
    name: shopify-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        value: <your_api_key>
      - key: SHOPIFY_API_SECRET
        value: <your_api_secret>
      - key: SHOPIFY_ACCESS_TOKEN
        value: <your_access_token>
      - key: SHOPIFY_API_VERSION
        value: 2025-07
      
    buildCommand: npm run build
    startCommand: node build/server/index.js
