client_id = "52829154ee8e87277ca412df5bda5ab2"
name = "Collection Tree"
application_url = "https://shopify-app-1-x1w5.onrender.com/"  # Render auto URL
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = ["https://shopify-app-1-x1w5.onrender.com/api/auth"]
